title: "Fingertip-Top - Content Design with Data and Code"
markdown: kramdown
tagline: "Put a finger on it"
description: "After I discovered coding, by Lovelli Fuad"
permalink: /blog/:year/:month/:day/:title
google_analytics: UA-82882327-1
highlighter: rouge
url: "http://fingertip.top"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
collections:
  werdz:
    output: true
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
  
