name: "Lovelli Fuad"
markdown: kramdown
description: "After I discovered coding, by Lovelli Fuad"
permalink: /blog/:year/:month/:day/:title
google_analytics: UA-82882327-1
plugins: 
  - jekyll-sitemap
